### ISSUE TITLE
Should endpoints be versioned

### ISSUE THREAD

**Issue by ashcrow** [zonggen/fcos-pinger-backend#2]
https://github.com/zonggen/fcos-pinger-backend/blob/master/main.go#L242 shows collection on `/`. Should the endpoint be versioned or should that be up to a proxy?

**Comment by zonggen** [comment]
By versioning you mean routing like `/data/minimal` and `/data/full`?

**Comment by ashcrow** [comment]
I mean more like the api itself. EG:

- /v1/[...]
- /v2/[...]
- etc ..

**Comment by zonggen** [comment]
That makes sense :+1: and I think both ways would work but adding versions at the endpoint makes more sense. If that's reasonable I will make a PR on this :)

**Comment by zonggen** [comment]
Just curious what would be the benefits of this, since we could enforce versions by doing releases or git branching.

**Comment by ashcrow** [comment]
Somewhat similar to https://kubernetes.io/docs/reference/using-api/api-overview/. If there is a change to the API you would be able to point new clients to `/v2` while old clients would still hit `/v1` until no clients used the old endpoint any longer. 

You can do this multiple ways ... some include:

1. Have the code mount `/v1/, `/v2/`, etc.. itself
2. Have each major release have a different endpoint within Openshift
3. Utilize a proxy in front which passes versioned routes to different containers

**Comment by zonggen** [comment]
Does the above PR seem reasonable?
The thought was to add API version in the form of request context inside a middleware and pass to the dataHandler. From there we could add additional functionality to the dataHandler according to the API version.

When the dataHandler grows in the future, we could remove the apiVersionMiddleware and use separate dataHandler for different API versions, e.g. dataHandlerV1, dataHandlerV2, ...

**Comment by ashcrow** [comment]
That should work :+1: . However, I'd suggest having different handler functions when a v2 is needed and map directly.  Anything that is common between versions likely should be their own functions.

**Comment by zonggen** [comment]
Indeed, separate functions -> separate of concerns -> better modularity

**Comment by zonggen** [comment]
Since the initial versioning is finished, closing..
